---
- hosts: web
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
      - name: Install dependencies
        apt:
            pkg:
                - git
                - python3-pip
                - libpq-dev
                - postgresql
                - postgresql-contrib
                - nginx
                - curl
                - python-is-python3
                - erlang
                - rabbitmq-server
            state: present

      - name: Install the gpg key for nodejs LTS
        apt_key:
            url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
            state: present

      - name: Install the nodejs LTS repos
        apt_repository:
            repo: "deb https://deb.nodesource.com/node_14.x focal main"
            state: present
            update_cache: yes

      - name: Install nodejs@14 from deb
        apt:
            name: nodejs
            state: present
