name: Django CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
          # Label used to access the service container
          postgres:
            # Docker Hub image
            image: postgres
            # Provide the password for postgres
            env:
              POSTGRES_DB: maestro_db
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
            # Set health checks to wait until postgres has started
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

        steps:
            # Downloads a copy of the code in your repository before running CI tests
            - name: Check out repository code
              uses: actions/checkout@v2
            # Sets up python
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9            
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run Migrations
              env:
                  DATABASE_NAME: maestro_db
                  DATABASE_USER: postgres
                  DATABASE_PASSWORD: postgres
                  DATABASE_HOST: localhost
                  DATABASE_PORT: 5432
              run: |
                  python manage.py migrate
            - name: Run Tests
              env:
                  DATABASE_NAME: maestro_db
                  DATABASE_USER: postgres
                  DATABASE_PASSWORD: postgres
                  DATABASE_HOST: localhost
                  DATABASE_PORT: 5432
              run: |
                  python manage.py test
